title: "迷妹精选 - 精品资源/图片/小说"
description: "搜罗网红视频、网红写真集、福利小说，迷妹精选只收录精品。"
url: 
baseurl: ""
author: "J0K1r"
paginate: 5
paginate_path: "/2022/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs